export const ADD_USER = "ADD_USER";
export const LET_USER_BE_LOGGED = "LET_USER_BE_LOGGED";
export const SHOW_ALL_USER_VAUCHERS = "SHOW_ALL_USER_VAUCHERS";
export const SHOW_ALL_VAUCHER = "SHOW_USER_VAUCHERS";
export const DID_USER_REGISTERED = "DID_USER_REGISTERED"
export const REMOVE_LOGGED_USER = "REMOVE_LOGGED_USER"